---
title: BDN Nodes
output: 
  html_document:
    includes:
      in_header: header_banner.html 
bibliography: PSref.bib
csl: ecology.csl  
---


## Fundamental objectives

1. Quantify PS recruitment to age 1. 
1. Provide relevant model inputs 
1. Quantify PS population trend
1. Maintain compatibility with legacy data 
1. Remain in cost constraints 




Quantify PS abundance or relative abundance	 
Quantify catch rates of age 0 and age 1 PS	 
Age at maturity	 
Age structure	 
Blood	 

Catch effort	 
Competition with invasive species	 
Contaminants	 
Didson	 
Diet	 
Disease	 
Drift and dspersal	 
 
Egg quality	 
Egg sample	 
Estimate Effective population size	 
Evaluate annual trends in Native forage fish	 
Fecundity	 
Fin ray	 
Fish communities	 
Fish condition	 
Foraging habitat	 
Free embryo collection	 
Genetic composition	 
Growth	 
Habitat selection	 
 
Hybridization	 
	 
IRC habitat	 
 
Local adaptation	 
 
Microchemistry	 
Model-based estimates of abundance of age 0 and age 1 PS	 
Model-based estimates of survival of hatchery and naturally reproducing PS to age 1	 
Movement	 
	 
Population estimates for PS for all size and age classes, particularly ages 2 to 3	 
Population structure and other characteristics	 
Predation	 
RNA Stress markers	 
Reproductive cycling	 
Reproductive readiness	 
Robust design	 
Sex	 
Sex ratio	 
Spawning aggregation and synchrony	 
Spawning habitat	 
Stable isotopes	 
Stocking program reports	 
 
Stress	 
Survival	 
	 
	 
	 
Use of Mississippi and tributaries	 
Zooplankton density	 
catch rates of all PS by size class	 


Hydroacoustic monitoring
N mixture model	 
PIT tag fish
Trawling
ultrasound
Telemetry River sweep
CJS	 
Calibrated Population Model	
Measure fish length and weight
Take a Tissue sample	
Lavage	 
Stomach removal	
EDNA	
Hatchery report and data	
Closed population estimaators
Smaller gill mesh
Use trammel nets
