# Estimating pallid sturgeon abundance and demographics in unmarked populations

## Introduction

## Methods

## Results

## Discussion


# Estimating pallid sturgeon abundance and demographics  in marked populations

## Introduction

## Methods

## Results

## Discussion


Survival

* Robust design
    * M0- varies by bend $\text{logit}(p)={{\beta }_{0}}+{{\beta }_{1}}\cdot Bend$
    * Mt – varies by bend and secondary occasion $\text{logit}(p)={{\beta }_{0}}+{{\beta }_{1}}\cdot Bend+{{\beta }_{2}}\cdot Occasion+{{\beta }_{3}}\cdot Bend\cdot Occasion$ 
    * Constant phi within segment, varies among years
        * $\operatorname{logit}(\phi )={{\beta }_{0}}+{{\epsilon }_{year}}$ where ${{\epsilon }_{year}}\tilde{\ }N(0,\sigma )$ 
* Robust design with telemetry 
    * In segment (perfect detection, imperfect detection)
    * River sweep (perfect detection, imperfect detection)
        * $\operatorname{logit}(\phi )={{\beta }_{0}}+{{\epsilon }_{year}}$ where ${{\epsilon }_{year}}\tilde{\ }N(0,\sigma )$ 
        * ${{Z}_{track,segement,year}}\tilde{\ }binomial({{\phi }_{segment,year}})$ 
        * River sweep to inform $\phi$, $\gamma \prime $, and $\gamma\prime\prime$from tracking tags
