---
title: "Post PSPAP Workshop Literature Suggestions"
output: 
  html_document:
    includes:
      in_header: header_banner.html 
---

<!---
rmarkdown::render_site("2017-05-15-Post-Workshop-Literature.Rmd")# build website
--->

Several folks contributed literature citations to the EA team during the 
PSPAP workshop. Those suggestions were appreciated and citations and 
links to those reports are below. 

* Schlosser, J. T. 2008. Large river fish community sampling strategies 
and fish associations to engineered and natural river channel 
structures. Masters thesis. Kansas State University, Manhattan, 
KS.[PDF](/pdfs/Large-River-Community-Sampling.pdf) 
* Saltzgiver, M. J., E. J. Heist, and P. W. Hedrick. 2012. Genetic 
evaluation of the initiation of a captive population: the general 
approach and a case study in the endangered pallid sturgeon 
(_Scaphirhynchus albus_). Conservation Genetics 13:1381-1391. 
[PDF](/pdfs/SaltzgiverCaptiveBroodstock2012.pdf) 
* Albers, J. L., M. L. Wildhaber, and A. J. DeLonay. 2013. Gonadosomatic 
index and fecundity of Lower Missouri and Middle Mississippi River 
endangered pallid sturgeon estimated using minimally invasive 
techniques. Journal of Applied Ichthyology 
29:968-977. [PDF](/pdfs/Pallid-reproductive-evaluation.pdf) 
* Doyle, W., C. Paukert, A. Starostka, and T. Hill. 2008. A comparison 
of four types of sampling gear used to collect shovelnose sturgeon in 
the Lower Missouri River. Journal of Applied Ichthyology 24:637-642. 
[PDF](/pdfs/shovelnose-gear-evaluation.pdf)
* Block, W.M., Franklin, A.B., Ward, J.P., Ganey, J.L., and White, G.C., 
2001, Design and Implementation of Monitoring Studies to Evaluate the 
Success of Ecological Restoration on Wildlife: Restoration Ecology, v. 
9, no. 3, p. 293-303, [PDF](/pdfs/Block-etal2001). 
* L.L. Pierce, D.A. James, D. A. Shuman, and R. A. Klumb. 2016. Pallid 
sturgeon detectability, catchability and post-handling survival with 
four standardized sampling gears, and movement of pallid sturgeon during 
the 2011 flood. Report prepared for the Western Area Power 
Administration, Billings, Montana and the Upper Basin Pallid Sturgeon 
Workgroup. [PDF](/pdfs/WAPA-Final-Report.pdf) 
    * Detectability objective (bend tracked for transmittered fish prior to 
    deploying PSPAP standard effort): 
    * Zero small (339-500 mm) pallid sturgeon located within sampled bends 
    were captured with otter trawls (1 bend sampled) and trammel nets (7 
    bends sampled), resulting in conditional capture probability estimates 
    of 0.00 for both gears. Three large (564-1105 mm) pallid sturgeon 
    located within sampled bends were captured with trotlines and one was 
    captured in a trammel net resulting in mean conditional capture 
    probability estimates of 0.36 (SE=0.18) for trotlines (N=7 bends), 0.13 
    (SE=0.13) for trammel nets (N=8), 0.00 for the otter trawl (N=6), and 
    0.00 for gill nets (N=5). 
    * Catchability objective (trammel nets drifted at known pallid sturgeon 
    location): 
    * Thirty-nine fish (23 small fish and 16 large fish) were targeted for 
    capture on 56 occasions (31 on small fish and 25 on large fish), 
    resulting in 210 trammel net drifts. 
    * Targeted pallid sturgeon were captured in 16 of the 56 (29%) attempts. 
    Capture probability of an individual drift (pi) for both size classes 
    (pooled) ranged from 0.00 to 0.11 (Table 3.3). The probability of 
    capture in multiple drifts (pi*) increased from 0.07 in one drift to 
    0.32 in five drifts (Table 3.3; Figure 3.2). 
    * Small pallid sturgeon were captured in nine of the 31 (29%) attempts. 
    All nine of these individuals were captured during the first four 
    drifts. Capture probability (pi) was greatest for the third drift 
    (0.13), followed by the fourth drift (0.10), second drift (0.07), and 
    the first drift (0.06; Table 3). The probability of capture in multiple 
    drifts (pi*) increased from 0.06 in one drift to 0.32 in four or more 
    drifts (Table 3.3; Figure 3.2). 
    * Large pallid sturgeon were captured during seven of the 25 (28%) 
    attempts. Capture probability (pi) was greatest for the fifth drift 
    (0.13), followed by the third drift (0.10; Table 3.3). The probability 
    of capture in multiple drifts (pi*) increased from 0.08 in one drift to 
    0.36 in five drifts (Table 3.3; Figure 3.2). 

