
# Estimating Pallid Sturgeon Abundance and Demographic Rates

## Robust Design Overview
The population assessment approach proposed is what is referred to as a 
robust design (Pollock 1982, Kendall 1997). As originally described by 
Pollock (1982), a robust design consists of primary sampling occasions 
with secondary sampling occasions nested with the primary sampling 
occasion. Primary occasions are spaced temporally to capture processes 
such as survival and growth. Secondary occasions occur over a short 
time frame, short enough that closure of the population from demographic 
processes (i.e., recruitment, mortality, immigration, emigration) can be 
assumed. The secondary sampling occasions also provide multiple 
opportunities for individuals to be captured, allowing for the 
estimation of capture probability providing an estimate of the 
population rather than an index of relative abundance. True abundance 
estimates are important to ongoing adaptive management and recovery 
because species recovery objectives and sub objectives are specified as 
abundance and population growth rate ($\lambda $) is estimated as 
$\lambda ={{N}_{t+1}}/{{N}_{t}}$ where $N$ is population abundance. 


The robust sampling design has been applied across a wide range of taxa 
to estimate demographic rates and population abundance. The robust 
design was originally conceived to provide a robust population estimates 
derived from open capture-recapture models, the Jolly Seber model in 
particular. Its use has been extended to studies of species occurrence 
(i.e., occupancy models; MacKenzie et al. 2002, Tyre et al. 2003) and 
abundance (N-mixture models; Royle 2004b, Royle 2004a) of unmarked 
individuals. Therefore it provides a rigorous framework that allows for 
the estimation of relevant demographic rates and abundance, using marked 
or unmarked individuals. It should be recognized that monitoring Pallid 
Sturgeon in a system as large as the Missouri River is inherently 
challenging and it is likely that any approached used will violate an 
assumption required to estimate demographic rates or population 
abundance. The following sections provide a preliminary overview of the 
robust design as a potential monitoring design for Pallid Sturgeon 
populations of the Upper and Lower Missouri River. 

          



# Basic Robust Design

## Overview

## Parameters for the robust design

* $\phi$ or $S$ is survival
* $c$ is initial capture probability
* $p$ is recapture probability
* $\Gamma$ is the seniority parameter
* $f_0$ is number of unobserved individuals
* $\gamma^{\prime}$ is the probability of 
* $\gamma^{\prime\prime}$ is the 

## Analysis objectives

<!-- source for existing analysis
```{r,echo=FALSE}
#source("./RD-Rmark/R/3-load.R")
#source("./RD-Rmark/R/4-clean.R")
#source("./RD-Rmark/R/5-figures.R")
#source("./RD-Rmark/R/6-tables.R")
#figures(1)
```
-->



Robust design	PSPAP
	PSPAP + telemetry	PSPAP + river sweep
	PSPAP + telemetry + river sweep
	
Robust design	Random reaches
	Random reaches + telemetry
	Random reaches + river sweep
	Random reaches + telemetry + river sweep
	
K160: Korman, J., J. Schick, and B. Mossop. 2016. Estimating Riverwide 
Abundance of Juvenile Fish Populations: How Much Sampling is Enough? 
North American Journal of Fisheries Management 36:213-229. 



* Robust design
    * M0- varies by bend $\text{logit}(p)={{\beta }_{0}}+{{\beta }_{1}}\cdot Bend$
    * Mt – varies by bend and secondary occasion $\text{logit}(p)={{\beta }_{0}}+{{\beta }_{1}}\cdot Bend+{{\beta }_{2}}\cdot Occasion+{{\beta }_{3}}\cdot Bend\cdot Occasion$ 
    * Constant phi within segment, varies among years
        * $\operatorname{logit}(\phi )={{\beta }_{0}}+{{\epsilon }_{year}}$ where ${{\epsilon }_{year}}\tilde{\ }N(0,\sigma )$ 
* Robust design with telemetry 
    * In segment (perfect detection, imperfect detection)
    * River sweep (perfect detection, imperfect detection)
        * $\operatorname{logit}(\phi )={{\beta }_{0}}+{{\epsilon }_{year}}$ where ${{\epsilon }_{year}}\tilde{\ }N(0,\sigma )$ 
        * ${{Z}_{track,segment,year}}\tilde{\ }binomial({{\phi }_{segment,year}})$ 
        * River sweep to inform $\phi$, $\gamma \prime $, and $\gamma\prime\prime$from tracking tags

        
1. Do fish move large distances outside of migrations? What is the 
optimal time to do capture-recapture? Options: none, some, a lot. 

2. What is better to estimate as a random subset of bends or randomly 
tag a bunch of fish and recapture in random bends? 


| Option 	|       Model       	| $N_{true}$ 	|               N Bends              	|   Occasions  	|
|--------	|:-----------------:	|:----------:	|:----------------------------------:	|:------------:	|
| V01    	| $p{{(.)}_{bend}}$ 	|    5000    	| 5,7,10,15,20,25,30,35,40,50,75,100 	| 4 to 10 by 1 	|
|        	|                   	|            	|                                    	|              	|
|        	|                   	|            	|                                    	|              	|		
				

      
River bends, defined as a outer bend and crossover were used to simulate spatial dynamics.  The location of individual Pallid Sturgeon were tracked during each time step and moved to a new bend, conditional on survival and previous bend location assuming a multinomial distirubtion as,

Loc_{j,t+\delta t}~Multinomial(p_{I,.,t}

Where variables and indices are defined in table xx. The vector of 
probabilities $p_{I,.,t}$ predicts the probable location given the 
previous bend location. This approach to movement provided a flexible 
approach to modeling movement that can be readily related to management 
actions. Specifically, $p_{I,j,t} is an array of probabilities with each 
row summing to one forming a 12 transition matrices providing the 
probility of moving from bend $i$ to bend $j$. This array of 
probabilities provides a plugin location for movement. The diagonal 
represents the probability of remaining in the same reach, off diagonal 
elements represent downstream or upstream movements. 


## Management effects on movement

The effect of management actions on movement or drift of adult or larval 
Pallid Sturgeon respectively can be simulated by modifying monthly 
transition matrices. For example, suppose that adult Pallid Sturgeon 
migrate upstream given a flow or temperature cue. This directed movement 
can be simulated by specifying the probability of a fish moving to 
downstream bends equal to 0 and upstream bends greater than 0. 
Similarly, the effect of flow on free embryo drift can be simulated with 
increased downstream probabilities. 


Y_{I,j,t+1}=\beta_0 + \beta_1 \cdot Q_{I,j,t} for i<=j
i>j = 0

Current model implementation requires an array of transitions for each 
time step. Future model versions will attempt to reefing the link 
between environmental covariates like flow such that a time series of 
predicted flows can be used as as inputs. The relationship between 
movement and varying covariates may take the form of a model prediction 
given previous location. For example, movement in terms of kilometers 
could be modeled 


$rkm_{t+1} = \beta_0 + \beta_1 \cdot Q + \beta_2 \cdot rkm_t + \beta_3 \cdot Q \cdot rkm_t + \sigma$.
   
The equation predicts how far, on average, a pallid sturgeon will move 
given an effect of flow and current location. The interaction term 
accounts for the effect of location (i.e., fish cannot move as far if 
they are near the uppermost bends). 

