---
title: "Overview of Pallid Sturgeon Assessment Framework Evaluation"
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "Missouri River Pallid Sturgeon Technical Team"
output:  
  html_document:
    theme: readable
    highlight: tango
  pdf_document:
    highlight: zenburn 
  word_document:
    highlight: zenburn
    fig_width: 6.5  
    fig_height: 6.5 
    reference_docx: tmp.docx
---

<!--
rmarkdown::render("_reboot-master-report.Rmd",
    output_format="word_document",
    output_file = paste(format(Sys.time(), '%Y%m%d'),
        "reboot-master-report.docx",sep="-"))# build page

To do:
* add overview document
* add document sections & organize them
-->


<!--Overview-->




<!--Text from white paper submitted to ISAP-->
```{r child="_white-paper.Rmd", echo=FALSE}
```

<!--Methods-->

<!-- Methods: workshop write up and documentation-->
```{r child="_objectives-hierarchy.Rmd", echo=FALSE}
```

<!--Methods: reference population-->
```{r child="_Reference-Population.Rmd", echo=FALSE}
```

```{r child="_Catch-Data.Rmd", echo=FALSE}
```
<!--Methods: decisions and decision space-->


<!--Methods: valuing design outcomes-utilities-->
```{r child="_utilities.Rmd", echo=FALSE}
```


# Results 
  * Number of bends for each RPMA

<!--
# Discussion
  * Virtual versus power analysis of a post-hoc glm to get trend

How did wildhaber and adam do it did they do virtual or just trend.

They did essentially the same thing, evaluating what the change in cpue
was rather than actually doing trend. In other words what is the power to 
detect a 10% decrease in the mean where mean cpue was estimated for each 
year but not as a function of year.
-->