---
title: "Generating AM Sub-Objective Metrics"
header-includes:
  - \usepackage{amsmath, graphicx}
output: 
  html_document:
    theme: readable
    highlight: tango
  word_document:  
    fig_width: 6.5  
    fig_height: 6.5 
    reference_docx: tmp.docx
---

<!--
rmarkdown::render("_Report-2-06-estimating-population-values.Rmd",output_format='word_document')# build page
-->

The need to redesign the PSPAP was triggered by the recognition that the 
current PSPAP may not allow evaluation of whether the pallid sturgeon 
fundamental objectives identified in the AM plan were achieved on an 
annual basis or estimated with any level of certainty. Specifically, 
sub-objectives listed in section 4.1.1. of the AM plan specify 1) 
increase pallid sturgeon recruitment to age-1, and 2) maintain or 
increase numbers of pallid sturgeon as an interim measure until 
sufficient and sustained natural recruitment occurs, both of which are 
needed to achieve the fundamental objective set by the USFWS to preclude 
species jeopardy. These two sub-objectives are redefined as fundamental 
objectives in the context of the monitoring program to detect and quantify 
recruitment to age-1 and quantify pallid sturgeon population trend and 
abundance. 

Metrics to assess achievement of the first sub-objective (increase 
pallid sturgeon recruitment to age-1) are particularly challenging 
because of the rarity of the species and existing technical difficulties 
with capturing age-1 (and age-2, age-3) fish and in accurately 
determining ages. As direct assessment of recruitment to age-1 is 
unlikely to be successful, the PSPAP v. 2.0 process has proceeded with 
the assumption that recruitment will need to be assessed through 
estimates of abundance and trend of older fish, determination of 
hatchery or wild origin, and back-calculation of age-1 recruitment rates 
through a well-calibrated and validated population model. As reported in 
Section 4.1.1 of the AM plan, metrics for assessing the second 
sub-objective (maintain or increase numbers of pallid sturgeon as an 
interim measure) include population estimates for pallid sturgeon for 
all size and age classes, where age classes are estimated by the 
population model.


As indicated above, estimates of abundance and trend are key to 
assessing both of the AM plan pallid sturgeon sub-objectives, and 
therefore, both the generation and the assessment of abundance and trend 
estimates play a key role in this analysis. Here we focus on the 
generation of the abundance and trend estimates, i.e. the metrics for 
assessing the AM sub-objectives, leaving the assessment of these 
estimates to the following section. 

<!--
Generating abundance and trend estimates under a particular monitoring 
design occurs in two steps:

1. Simulate catch data using the sampling design prescribed by the 
given monitoring program, and
2. Calculate estimates from the catch data using the abundance and trend
estimators prescribed by the given monitoring program.

Since the simulation of catch data is stochastic and certain values 
(e.g., catchability) are uncertain, these steps were repeated several 
times for each monitoring design, generating a fuller picture of the 
range of outcomes that can be expected under a particular monitoring 
design.
-->


### Objectives
The objectives of estimating population metrics are, for each monitoring 
design considered and for each of the catch data sets generated under the 
given monitoring design, to:

1. Generate an estimate of the average population trend over the 10-year 
period by basin,
2. Generate segment-level abundance estimates (as inputs for the collaborative population model, PSPAP Fundamental Objective 3) by length class, and
3. Generate basin-level abundance estimates by aggregating segment-level estimates.
  

### Major Assumptions
We made the typical assumptions associated with the use of each 
individual estimator. In general, these assumptions match the 
assumptions used to generate the reference populations and 
simulate the catch data. Any major assumptions additional to 
those previously discussed are included in the discussion of the 
particular estimator to which it applies. 



<!--# Methods-->
### Scope and Spatial Scale
Since accurately identifying fish age in the field is challenging and 
the AM plan specifies that age classes are to be estimated by the 
collaborative population model, we limit our current focus to overall 
population estimates for pallid sturgeon, as well as population 
estimates by size class. 

Whenever possible, population abundance estimates were made at the bend 
level and then aggregated to the segment level; however, monitoring 
designs that employed the robust design abundance estimator had 
difficulty producing estimates at the bend spatial scale.  Therefore, 
all monitoring designs using the robust design estimator directly 
estimated segment-level abundances.

### Monitoring Design Estimators
Several capture-recapture estimators exist to estimate abundance, 
demographic rates, as well as abundance and demographic rates. A capture 
recapture estimator that simultaneously estimates demographic rates and 
abundance can potentially achieve metrics and targets specified in 
sub-objectives 1 and 2. Historically, a Jolly-Seber model, was used to 
simultaneously estimate abundance and survival from recapture of marked 
individuals from singular capture occasions over time (Jolly 1963, 1965, 
Seber 1965). However, the lack of multiple within primary occasion 
recapture attempts required potentially unrealistic assumptions to 
estimate capture probability.  By considering monitoring designs that 
utilitze multiple recapture efforts (secondary occasions) within a 
sampling year (primary occasions), direct estimation of capture 
probability can be achieved, opening the door to the use of several mark-
recapture estimators. 
 
#### Abundance Estimators
##### Minimum Known Alive
The minimum known alive (MKA) estimator is the most simplistic abundance 
estimator we considered.  It does exactly what it sounds like: it uses 
the number of (unique) individuals captured in a bend as an estimate for 
the bend abundance.  This estimator is expected to be very negatively 
biased, as, given low capture probabilities and reasonable effort, it is 
likely we catch only a small portion of the fish living in the bend. 
However, this estimator has its benefits:  

* It does not require a mark-recapture program (i.e., it can be used 
with single occasion data), and therefore, should save on costs, and
* It can be used with mark-recapture program data when more 
sophisticated estimators fail to produce estimates.

For these reasons, we ran the MKA estimator under all monitoring program 
sampling designs, allowing us to compare it to all other estimators. 
For single occasion data, the bend level abundance estimate is the same 
as the number of fish caught in the bend.  For multiple occasion data, 
PIT tag identification of the fish caught will be necessary.  Using PIT 
tag information, it can be determined if any fish were caught multiple 
times (in different occasions).  Each fish that was caught will be 
counted only once, whether or not it was caught during more than one 
occasion.  The total number of unique fish known to be alive in the 
bend, as determined from PIT tag identification, serves as the estimate 
for bend abundance.  

Assuming PIT tag identification is always reliable,
then the MKA abundance estimate is always clear and estimate standard 
error is 0 at the bend level.  However, non-zero standard errors were 
calculated when we aggregate bend level estimates to the segment or 
basin levels (See Aggregating bend level abundance to segment level).

##### Closed mark-recapture estimators, M$_0$ and M$_t$
The closed mark-recapture estimators take advantage of multiple capture 
occasions within a year to estimate both capture probability and
abundance.  The two estimators differ in the way they treat capture 
probability.  The M$_0$ estimator assumes that the capture probability 
is constant across all capture occasions ($p$).  The  M$_t$ estimator 
assumes that capture probability varies within a year from occasion to 
occasion ($p_t$).  

In reality, we can expect capture probability to vary from occasion to 
occasion due to many factors (e.g., water velocity, temperature); 
however, if fluctuations in capture probability are expected to be small, 
then capture probability may best be modelled as a constant with some 
environmental noise.  In this case, the M$_0$ estimator is likely the 
best choice of the two.   On the other hand, if different gears are used 
during each capture occasion and we expect that the different gears will 
have a large difference in capture probability, then the M$_t$ estimator
may be the better choice.  In any of these cases there may be a tradeoff 
between estimating more parameters (multiple capture probabilities) and 
the bias and precision of thes pararmeter estimates.  Therefore, we 
implemented both the M$_0$ and the M$_t$ estimators in all scenarios and 
compared their outcomes.  

Both the M$_0$ and M$_t$ estimators rely on the assumption that the 
population is closed across capture occasions; in other words no fish 
moves into the sampled bend or out of the sampled bend during the time 
period between the start of the first capture occasion to the end of the 
last within year capture occasion.  In the analysis of monitoring 
programs presented here, this assumption will hold as it was one of the 
assumptions used to generate the reference population.  This allows us 
to evaluate the performance of these estimators under the best of 
circumstances.  If they do not perform well in these circumstances, then 
it is unlikely they will perform well in others. 

We assumed a single capture occasion will be approximately a 24-hour 
time period, so for the case of actually sampling pallid sturgeon in the 
Missouri River, we would want this assumption of no movement to 
approximately hold for at least a few days.  Additionally, since it is 
likely this assumption will not be met consistently in the field, we 
have looked at the consequences of breaking the assumpiton of closure 
across capture occasions (See ??).

We ran the M$_0$ and M$_t$ estimators in R using the $\texttt{closedp.t}$ 
function in the $\texttt{Rcapture}$ package, obtaining bend abundance 
estimates and estimate standard error.  Any estimator results that gave 
estimates but produced warnings (e.g., nonconvergence, extremely large 
asymptotic bias) were excluded from the analysis (with the exception 
that the inability of the estimator to produce estimates is considered 
in estimator utility). 

The M$_0$ and M$_t$ estimators only analyze the data from within a year 
and do not compare data across years.  Therefore, while these estimators 
can produce estimates of capture probability and annual bend level 
abundance, they cannot estimate annual survival or recruitment.


##### Robust Design
The robust design estimator (RD) takes the analysis of capture recapture 
data a step further than the closed mark-recapture estimators described 
above.  It uses multiple capture occasions within a year, as well as 
comparing capture data across years in order  to directly estimate 
capture probability, abundance, and survival as described by Pollock 
{Pollok 1982}.


The robust design frame work has been applied across a wide range of 
taxa to estimate demographic rates and population abundance. Its use has 
been extended to studies of species occurrence (i.e., occupancy models; 
{MacKenzie et al. 2002, Tyre et al. 2003}) and abundance (N-mixture 
models; {Royle 2004b, Royle 2004a}) of unmarked individuals. The robust 
design provides a rigorous framework that allows for the estimation of 
relevant demographic rates and abundance using marked individuals. As 
originally described by Pollock {1982}, a robust design consists of 
primary sampling occasions (e.g., years) with secondary sampling 
occasions nested within each primary occasion (Figure 1). 
Primary occasions are spaced temporally to capture processes like 
survival and growth. Secondary occasions occur over a short time frame, 
short enough that closure of the population from demographic processes 
(i.e., recruitment, mortality, immigration, emigration) can be assumed. 
The secondary sampling occasions provide multiple opportunities for 
individuals to be captured and thereby allowing capture probability and 
abundance to be estimated.

The use of a robust design capture recapture approach to estimate 
Missouri River pallid sturgeon abundance, and demographic rates are not 
novel. The first application was Steffensen et al. (2012) as part of the 
annual brood stock collection in segment 9. Similarly, Winders and 
Steffensen (2014) used a robust design to estimate abundance and 
demographic rates for a portion of segment 10 using broodstock 
collection data. In both studies, pallid sturgeon were captured by 
setting multiple trotlines at random locations in the study area over a 
short period. The annual brood stock sampling was the primary occasion 
and daily capture efforts were the secondary occasions in both studies. 
Given the study design, survival was estimated over the open period 
(i.e., between annual broodstock collection events). Capture probability 
was estimated for each daily effort within the primary period and 
abundance during the closed period (i.e., broodstock collection). 
Additionally, both studies were able to estimate movement parameters 
that account for pallid sturgeon leaving or arriving in the study area 
between closed periods. 

There are variations of the robust design that estimate alternative sets 
of parameters. The most commonly used version, as well as the version 
used by Steffensen et al. (2012) and Winders and Steffensen (2014) is 
the version that estimates 6 parameters. Specifically these parameters 
are: 

* $\varphi$: the probability of surviving between primary occasions, 
* $\gamma^{\prime}$:  the probability of being outside the study area and unavailable for capture during the primary occasions given the animal was not present during the previous primary occasions given it survives to the current occasion (Figure 2),
* $\gamma^{\prime\prime}$:  is the probability of being outside the study area and unavailable for capture during the primary occasions given the animal was present during the previous primary occasions given it survives to the current occasion (Figure 2),
* $c$ is the initial capture probability,
* $p$ is the recapture probability, and 
* $f_0$ is number of unobserved individuals.  

Depending on the situation the number of parameters estimated can be 
reduced by assuming initial capture probability is equal to recapture 
probability where $c=p$. Similarly, ${{\gamma }^{\prime }}$ and 
$\gamma^{\prime\prime}$ can be specified to represent hypotheses about 
immigration and emigration processes. For example, even flow of fish in 
and out of the systems can be specified by imposing equality of 
immigration and emigration terms where ${{\gamma }^{\prime }}={{\gamma 
}^{\prime \prime }}$. Population abundance ($N$) at each time period is 
a derived parameter calculated as: $N={{f}_{0}}+M$ where, $M$ is the 
number of marked fish. Uncerainty around derived parameter estimates can 
be estimated by profile likelihood and use of the delta method if 
estimated by maximizing the likelihood of the model given the data 
{Hilborn and Mangel 1997, Powell 2012}. Uncertainty can also be 
quantified simultaneously for estimated and derived parameters if fit by 
MCMC using a Bayesian approach. 

We used what is known as the closed robust design multi-state model
(CRDMS).  Between year movment from bend to bend or segment to segment 
may lead to individuals being collected in one sampling area (i.e., 
state) one year and another sampling area a future year.  A multi-state 
model takes into consideration this movement by looking at and comparing 
capture histories from all connected states, allowing the estimation of 
transistion probabilities, or the probability that a fish moves from one 
state to another.  In this case, all the parameters listed above are 
estimated, with the exception of the two gamma parameters ($\gamma'$ and 
$\gamma''$), as movement into and out of the sampling (or observable 
area) is now taken into account with the transition probabilities:

* $\psi_{ij}$: the transition from state $i$ to state $j$, where a state 
is either a sampling unit or the unobservable area outside all sampling 
units. 

For example, if we sample segments 7-10,13 and 14 in the lower Missouri, 
the multi-state model will provide transition probabilities from each of 
these segments to each of the other segments, as well as transition 
probabilities to an unobservable area (e.g. temporary migration to the 
Platte or Mississippi).

We attempted to run the CRDMS model through R using Program MARK at the 
bend level (where each observable state would be a sampled bend); 
however, either the capture history data available (lack of enough 
recaptures), the computation time needed, or the memory needed caused 
issues with obtaining estimates from the estimator.  We were, however, 
able to run the estimator at the segment level, running seperate 
estimates for each basin since basins are assumed unconnected by natural 
movement.  This allowed for the estimation of segment level abundances 
and transition probabilities, as well as basin level annual survival and 
capture probability, where we assumed capture and recapture 
probabilities were equivalent (i.e, $c=p$). 




#### Trend Estimators
We defined trend as the population growth rate $\lambda$, 
which describes how quickly the population is either growing 
($\lambda>1$) or declining ($\lambda<1$) each year.  Trend, therefore, 
takes into account both survival and recruitment. 

##### Abundance Based Estimators
In general, we can define population growth as
$$N_t=\lambda^t N_0,$$
where $N_t$ is the population size in year $t$ and $N_0$ is the initial 
population size.  If we take the natural logarithm of both sides of this 
equation we find
$$\ln(N_t)=\ln(\lambda)\cdot t + \ln(N_0).$$
In other words, abundance on a log-scale is a linear model with a slope 
directly related to $\lambda$.  We use this relationship to our 
advantage, fitting a linear model to the log-transformed segment level 
estimated abundances in order to estimate the average population trend, 
$\lambda$.  In particular we fit the model

$$\log(abundance)\sim segment+year,$$

taking into account the effect segment has on the relationship.

This model was fit to segment level abundance estimates generated 
by each of the abundance estimators described above, resulting in 7 
abundance based trend estimators (2 for each of MKA, M$_0$, and M$_t$--- 
see Aggregating bend level abundance to segment level---and 
one for the CRDMS, or robust design estimator).  The estimated slope 
($\hat{\beta}$) of the linear model and its standard error, were 
then used to estimate the average trend:
$$\hat{\lambda}=e^{\hat{\beta}}$$
with standard error 
$$e^{\hat{\beta}}\cdot SE(\beta),$$
as calculated using a first order approximation under the delta method, 
where $SE(\beta)$ is the standard error of the slope estimate $\beta$.


##### Catch Effort
The catch effort estimator assumes that catch per unit effort (CPUE) is 
proportional to abundance, which is indeed as we modeled it in the 
catch data:
$$C=qfN,$$
where $C$ is catch, $q$ is catchability described as the probability of 
capturing a single fish with one unit of effort, $f$ is effort (in this 
case, measured in minutes of gear deployment), and $N$ is abundance. 
Therefore, we would expect CPUE (or $C/f$) to be proportional to 
abundance.  Consequently, the log-transformed CPUE is also a linear 
function of the log-transformed growth rate, $\lambda$, justifying the 
use of the same approach as in the case of abundance, but instead 
fitting the linear model

$$\log(\mbox{CPUE})\sim segment+year,$$

to the segment level catch effort data.  One issue with this approach, 
however, is that zero catch values cannot be log-transformed.  To avoid 
problems that arise due to zero catch values the Catch Effort Trend 
estimator instead adjusts the CPUE by adding one to the catch prior to 
dividing by the effort, i.e.,
$$\tilde{\mbox{CPUE}}=\frac{C+1}{f}   \hspace{0.5cm} \mbox{ and } \hspace{0.5cm}
\log(\tilde{\mbox{CPUE}})\sim segment+year.$$

It is from this linear model that the estimate for $\lambda$ and its 
standard error are calculated, using the same equations described for 
the abundance based trend estimators above.

##### Pradel
When capture recapture histories are viewed in reverse order 
recruitment can be estimated using what is referred to as a Pradel model 
(Pradel 1996). This model relies on being able to differentiate recruits 
based off of size or age which works well for fish populations. 
Therefore there are 2 processes in which a pallid sturgeon can be 
initially captured: 1) it is a new recruit and was not vulnerable to 
capture and 2) the pallid sturgeon was vulnerable to capture but not 
captured. The differentiating the 2 outcomes can be informed by size to 
improve recruitment estimates. 

In addition to estimating recruitment the Pradel estimator can also 
estimate survival, allowing for an estimation of population trend to be 
derived.

##### Direct Estimation from Robust Design
While not commonly employed in fisheries literature the robust design 
can estimate population growth rate ($\lambda$). In particular, by 
running capture histories backwards estimates the probability a pallid 
sturgeon was present in the previous year given it was present in the 
current year which is the per capita rate of additions to the population 
($f$), or the number of individuals entering the population between 
primary occasions. Survival rate ($\varphi $) can be estimated, and by 
running them forward, survival can be estimated. Trend evaluated as 
population growth rate is derived from model estimates as$\lambda 
=\varphi \text{+}f$ and uncertainty can be estimated using the 
previously described approaches for$N$.


#### Aggregating Bend Level Abundance to the Segment Level
The minimum known alive (MKA) and closed mark-recapture M$_0$ and M$_t$ 
estimators were ran to estimate abundance at the bend level.  However, 
abundance estimates at the segment and basin levels are desired for use 
in PSPAP Objectives 3 and 2, respectively.  Here we'll discuss the 
aggregation of the MKA, M$_0$, and M$_t$ abundance estimates to the 
segment level, leaving discussion of the basin level estimates to the 
next section.

Aggregation to the segment level was based on estimated bend level 
densities, or the estimated bend abundance divided by the bend length in 
river kilometers (rkm). We assume the segment density can be estimated 
by the average density of pallid sturgeon in the sampled bends within 
the segment.  Therefore, the segment abundance can be estimated as the 
estimated segment density multiplied by the length (in rkm) of the 
segment.

In calculating the average density of pallid sturgeon in a segment we 
took two approaches for the purposes of comparing: arithmetic mean bend 
density and weighted mean bend density.  While we expect the weighted 
mean approach to be more accurate, we suspect that the arithmetic mean 
is a reasonable and commonly used approach, and therefore, wanted to 
highlight the differences between the two.

##### Arithmetic Mean (AM)
For the arithmetic mean method, we calculate the estimated densities of 
each sampled bend and then take the typical average (add up the 
densities and divide by the total number of bends sampled).  This 
averaged density is used as an estimate of the segment density.  The 
segment abundance is then calculated from the segment density estimate 
and segment length.  Mathematically, the segment abundance estimate is 
calculated as 
$$\hat{N_s}=\frac{\sum_i\left(\frac{\hat{N}_{s,i}}{L_{s,i}}\right)}{bends_s}\cdot L_s,$$
where $\hat{N_s}$ and $L_s$ are the estimated abundance and total length 
(in rkm) of segment $s$, repsectively, $\hat{N}_{s,i}$ and $L_{s,i}$ is 
the estimated abundance and length (in rkm) of sampled bend $i$ within 
segment $s$, respectively, and $bends_s$ is the number of sampled bends 
in segment $s$.

A potential issue with the arithmetic mean is that it treats each bend 
as equivalent to any other bend, despite the fact that bends are of 
different lengths.  To get a good understanding of how this can effect 
an estimate, let's look at a simplified example with known abundances 
(i.e. perfect estimates). 

EXAMPLE HERE


##### Weighted Mean (WM)
The weighted mean estimator attempts to remedy the issues discussed in 
the previous example that can arise from treating all bends as equal by 
weighting the bend densities. In particular, the weight for a bend is 
the length of that bend relative to the total length of all sampled 
bends within the segment, or,
$$w_{s,i}=\frac{L_{s,i}}{\sum_{j \epsilon J} L_{s,j}},$$
where $w_{s,i}$ and $L_{s,i}$ are the weight and length of sampled bend 
$i$ in segment $s$, respectively, and the set $J$ is the set of all 
sampled bends in segment $s$.  

The weighted mean density is then calculated as the sum of each bend 
density multiplied by its wieght, or, 
$$\hat{d}_s=\sum_{j \epsilon J} w_{i,s}\cdot \hat{d}_{i,s},$$
where $\hat{d_s}$ is the estimated segment density and $\hat{d}_{i,s}=\hat{N}_{i,s}/L_{i,s}$ 
is the estimated density of sampled bend $i$ in segment $s$.  While this 
calculation might seem unusual, when all is said and done, it is really 
just the total estimated abundance in the sampled bends (add all sampled 
bend abundance estimates together) divided by the total length of the 
sampled bends (add all sampled bend lengths togher) within the river 
segment, i.e., 
$$\hat{d}_s=\frac{\sum_{j \epsilon J} \hat{N}_{i,s}}{\sum_{j \epsilon J} L_{i,s}}.$$


The weighted mean estimated segment density is then turned into an 
estimated abundance in the same way it was for the arithmetic mean: by 
multiplying the estimated segment density by the length of the segment 
in river kilometers:  
$$\hat{N}_s=\frac{\sum_{j \epsilon J} \hat{N}_{i,s}}{\sum_{j \epsilon J} L_{i,s}}\cdot L_s.$$
So for our example, we have

EXAMPLE HERE

##### Standard Error
For the M$_0$ and M$_t$ estimators the segment level standard error was 
calculated using the delta method {Powell 2012} for both aggregation 
approaches.  Since non-zero bend level standard errors were not 
available for the MKA estimator (See MKA estimator description above), 
segment level standard errors were calculated using the variance in the 
bend level densities under the given approach:
$$Var(d_{s,i})=\sum_{j\epsilon J}  (\hat{d}_{s,i}-\hat{d_s})\cdot p_{s,i},$$
where $p_{s,i}=1/bends_s$ for the arithmetic mean approach and 
$p_{s,i}=w_{s,i}$ for the weighted mean approach.  The standard error is 
then calculated as the square root of the variance.  
<!--we might need to adjust this for comparison: N_s=d_s*RKM which the delta method can be applied to...although same approach above could be applied to all other estimators ignoring their SE's so we should address this somewhere in the discussion.-->


#### Aggregating Segment Level Abundanc to the Basin Level
Segment level estimates were aggregated to the basin level using the 
weighted mean approach described above with standard errors calculated 
using the delta method.

#### Quantifying effects of management actions and auxiliary information

Parameters in capture recapture models can be related to covariates 
which provide a potential means to quantify the population response to 
management actions. For example, changes in flow can be related to 
survival or migration parameters using a logit linear model 
as$\operatorname{logit}(\theta )={{\beta }_{0}}+{{\beta }_{1}}\cdot 
X+\epsilon $, where $\theta$ is an estimated parameter (e.g., $\phi$, 
$\gamma \prime$, $\gamma\prime\prime$), $\beta_0$ is the intercept, 
${{\beta }_{1}}$ is the effect of covariate $X$, and $\epsilon $ is 
residual error. Additionally, auxiliary information can be used to 
inform parameter estimates. For example, telemetry can be used to 
determine whether a pallid sturgeon is in the study area or not and 
thereby inform estimates of $\gamma \prime$and $\gamma\prime\prime$. 
Overall ability of a capture recapture robust design to use auxiliary 
information and potential capture population level responses to 
management actions make this a potentially useful design beyond 
providing a means to quantify the metrics and targets for sub-objectives 
1 and 2. 


#### Caveats and considerations
Monitoring pallid sturgeon in a system as large as the Missouri River is 
inherently challenging and it is likely that any approaches used will 
violate an assumption required to estimate demographic rates or 
population abundance. The previous section provides an overview of the 
robust design as a monitoring design for pallid sturgeon populations of 
the Upper and Lower Missouri River. The accurate estimation of 
population parameters represents a critical component of assessing the 
system state for pallid sturgeon in the Missouri River and providing key 
demographic values for evaluating management actions through predictive 
population modeling. The estimation of these metrics depends on the 
quality and quantity of data collected from a well-developed sampling 
design. The optimal design must be cost-efficient, and provide reliable, 
accurate data. 

Implementing an untested design on a large system like the Missouri 
River could prove costly from the expenditure of time and effort if the 
selected design performs poorly. Pallid sturgeon populations in the 
Upper and Lower Missouri Rivers differ (e.g., size and age at maturity, 
growth rates, life span). The habitats in which they live are also 
different. The Lower River is characterized by a narrow, self-scouring 
channel with higher water velocities, especially in the main channel. In 
contrast, the Yellowstone and Upper Missouri Rivers are characterized by 
lower velocities, shallower depths, and a more natural channel form. 
Differences between the two Missouri River portions has shown that the 
most effective sampling methodologies and potential strategies also 
differ significantly and therefore necessitate that the mark-recapture 
sample designs be tailored to each population. Provisional capture 
recapture population monitoring designs need to be evaluated by 
simulation modeling to identify the optimal design (that is, tradeoffs 
between precision, bias, and cost) and provide proof of concept before 
testing or implementing in the field as part of a level 1 science effort 
and adjusted periodically to improve the design so that it more 
effectively meets the monitoring and species objectives. 



<!--
Applications of Capture-Recapture Robust Design to PSPAP

The fundamental species objective identified by the USFWS for the pallid 
sturgeon is: Avoid jeopardizing the continued existence of the pallid 
sturgeon from the US Army Corps of Engineers actions on the Missouri 
River. Means to achieve this fundamental objective included increasing 
pallid sturgeon recruitment and maintaining or increasing current 
population levels. 

The means to achieve the fundamental objective are specified as 2 
sub-objectives with quantifiable metrics and targets as: 

1. Increase pallid sturgeon recruitment to age 1
Metric:  Catch rates of age 2 and 3 year-old pallid sturgeon.  
Target: Short-term: recruitment; long-term: projection from population 
models of an annual egg to age-1 survival rate > 0.03. 

2. Maintain or increase numbers of pallid sturgeon until sufficient and 
sustained natural recruitment occur. 

Metric:  Catch rate of all size classes 
Target: Viable population size necessary to successfully overcome 
recruitment bottleneck. Minimum of 5000 adults in each management unit. 


While a catch per unit effort based approach to population monitoring 
may be used to calculate the metrics for sub-objective 1 and 2 it fails 
to estimate sub-objective targets. Specifically, CPUE is a relative 
index of population abundance and therefore it may document recruitment 
if age-0 and age-1 pallid sturgeon are captured but it does not estimate 
early life history survival rates. Absolute population estimates cannot 
be achieved unless gear-specified catchability coefficient exists or can 
be estimated to link catch and effort to predict abundance 
as:$Abundance=Catch/ (Effort\cdot Catchability)$. Catchability 
coefficients are difficult to estimate, unlikely to be constant (i.e., 
gear-specific catchability varies among habitat type, season, fish 
species), and assumed to be constant across abundance levels. 
Catchability assumptions have received some scrutiny through 
meta-analysis of multiple fish stocks which suggest that fish stocks 
exhibit a curvilinear relationship of catchability with abundance, most 
commonly exhibiting a phenomenon known as hyperstability, where CPUE 
remains while abundance declines (Harley et al. 2001). It should be 
noted that gear-specific catchabilities have not been estimated for 
pallid sturgeon. The consequences of violating CPUE assumptions are 
uncertain. Despite this uncertainty, the CPUE based PSPAP has been 
successful in achieving PSPAP objectives, however, modifications will be 
needed to achieve sub-objective 1 and 2. 


Modifying the existing PSPAP program will ideally maintain a degree of 
compatibility with existing data while providing population level 
estimates of recruitment, trend, and abundance to achieve the metrics 
and targets specified in sub-objectives 1 and 2. Compatibility with 
existing PSPAP data can be achieved by maintaining the existing sampling 
framework where each management unit is divided into segments, river 
segments divided into bends, and habitat units sampled with each bend. 
Additionally, continued use of current PSPAP standard gear types defined 
in Welker et al. (2016), which have been identified over the duration of 
the PSPAP to be effective, will potentially maintain compatibility with 
existing PSPAP data. A significant modification will be required to 
estimate population abundance, specifically the use of a 
capture-recapture estimator to estimate demographic rates and abundance. 

Several capture-recapture estimators exist to estimate abundance, 
demographic rates, as well as abundance and demographic rates. A capture 
recapture estimator that simultaneously estimates demographic rates and 
abundance can potentially achieve metrics and targets specified in 
sub-objectives 1 and 2. Historically, a Jolly-Seber model, was used to 
simultaneously estimate abundance and survival from recapture of marked 
individuals from singular capture occasions over time (Jolly 1963, 1965, 
Seber 1965). However, the lack of multiple within occasion recapture 
attempts required potentially unrealistic assumptions to estimate 
capture probability. Some of these assumptions can be relaxed by 
sophisticated model formulations or fitting the capture recapture model 
as a Bayesian state space model, which has been done for pallid sturgeon 
in the RPMA 4 by Wu and Holan (2016). Alternatively, using multiple 
recapture efforts within a sampling occasion allows direct estimation of 
capture probability as well as abundance and survival, which was 
described by Pollock (1982) and referred to as the robust design. 

The robust design frame work has been applied across a wide range of 
taxa to estimate demographic rates and population abundance. Its use has 
been extended to studies of species occurrence (i.e., occupancy models; 
MacKenzie et al. 2002, Tyre et al. 2003) and abundance (N-mixture 
models; Royle 2004b, Royle 2004a) of unmarked individuals. The robust 
design provides a rigorous framework that allows for the estimation of 
relevant demographic rates and abundance using marked individuals. As 
originally described by Pollock (1982), a robust design consists of 
primary sampling occasions with secondary sampling occasions nested with 
the primary sampling occasion (Figure 1). Primary occasions are spaced 
temporally to capture processes like survival and growth. Secondary 
occasions occur over a short time frame, short enough that closure of 
the population from demographic processes (i.e., recruitment, mortality, 
immigration, emigration) can be assumed. The secondary sampling 
occasions provide multiple opportunities for individuals to be captured 
and thereby allowing capture probability and abundance to be estimated. 

Application of robust design to Pallid Sturgeon
The use of a robust design capture recapture approach to estimate 
Missouri River pallid sturgeon abundance, and demographic rates are not 
novel. The first application was Steffensen et al. (2012) as part of the 
annual brood stock collection in segment 9. Similarly, Winders and 
Steffensen (2014) used a robust design to estimate abundance and 
demographic rates for a portion of segment 10 using broodstock 
collection data. In both studies, pallid sturgeon were captured by 
setting multiple trotlines at random locations in the study area over a 
short period. The annual brood stock sampling was the primary occasion 
and daily capture efforts were the secondary occasions in both studies. 
Given the study design, survival was estimated over the open period 
(i.e., between annual broodstock collection events). Capture probability 
was estimated for each daily effort within the primary period and 
abundance during the closed period (i.e., broodstock collection). 
Additionally, both studies were able to estimate movement parameters 
that account for pallid sturgeon leaving or arriving in the study area 
between closed periods. 


Specific parameters estimated by the robust design
There are variations of the robust design that estimate varying 
parameters. The most commonly used version, as well as the version used 
by Steffensen et al. (2012) and Winders and Steffensen (2014) is the 
version that estimates 6 parameters. Specifically these parameters are: 

* $\varphi $: the probability of surviving between primary occasions, 
* $\gamma^{\prime}$:  the probability of being outside the study area and unavailable for capture during the primary occasions given the animal was not present during the previous primary occasions given it survives to the current occasion (Figure 2),
* $\gamma^{\prime\prime}$:  is the probability of being outside the study area and unavailable for capture during the primary occasions given the animal was present during the previous primary occasions given it survives to the current occasion (Figure 2),
* $c$ is the initial capture probability
* $p$ is the recapture probability, and 
* $f_0$ is number of unobserved individuals.  

Depending on the situation the number of parameters estimated can be 
reduced by assuming initial capture probability is equal to recapture 
probability where $c=p$. Similarly, ${{\gamma }^{\prime }}$ and 
$\gamma^{\prime\prime}$ can be specified to represent hypotheses about 
immigration and emigration processes. For example, even flow of fish in 
and out of the systems can be specified by imposing equality of 
immigration and emigration terms where ${{\gamma }^{\prime }}={{\gamma 
}^{\prime \prime }}$. Population abundance ($N$) at each time period is 
a derived parameter calculated as: $N={{f}_{0}}+M$ where, $M$ is the 
number of marked fish. Uncerainty around parameter estimates derived 
quantities can be estimated by profile likelihood and use of the delta 
method if estimated by maximizing the likelihood of the model given the 
data (Hilborn and Mangel 1997, Powell 2012). Uncertainty can also be 
quantified simultaneously for estimated and derived parameters if fit by 
MCMC using a Bayesian approach. 



Achieving sub-objective metrics and targets

Recruitment

When capture recapture histories are viewed in reverse order 
recruitment can be estimated using what is referred to as a Pradel model 
(Pradel 1996). This model relies on being able to differentiate recruits 
based off of size or age which works well for fish populations. 
Therefore there are 2 processes in which a pallid sturgeon can be 
initially captured: 1) it is a new recruit and was not vulnerable to 
capture and 2) the pallid sturgeon was vulnerable to capture but not 
captured. The differentiating the 2 outcomes can be informed by size to 
improve recruitment estimates. 

Trend

While not commonly employed in fisheries literature the robust design 
can estimate population growth rate ($\lambda$). In particular, by 
running capture histories backwards estimates the probability a pallid 
sturgeon was present in the previous year given it was present in the 
current year which is the per capita rate of additions to the population 
($f$), or the number of individuals entering the population between 
primary occasions. Survival rate ($\varphi $) can be estimated, and by 
running them forward, survival can be estimated. Trend evaluated as 
population growth rate is derived from model estimates as$\lambda 
=\varphi \text{+}f$ and uncertainty can be estimated using the 
previously described approaches for$N$. 

Abundance

Absolute abundance estimates are important to ongoing adaptive 
management and recovery because species recovery sub-objective 2 is 
specified as abundance. The robust design for capture recapture provides 
the necessary within primary occasion replication to reliably estimate 
capture probabilities ($c,p$) and then estimate $N$ given the number of 
fish captured and the capture probability. Given that the capture 
recapture design is potentially using 2 or more temporal replicates 
within each bend then unadjusted catch numbers may be comparable to 
existing PSPAP CPUE data. 


Quantifying effects of management actions and auxiliary information

Parameters in capture recapture models can be related to covariates 
which provide a potential means to quantify the population response to 
management actions. For example, changes in flow can be related to 
survival or migration parameters using a logit linear model 
as$\operatorname{logit}(\theta )={{\beta }_{0}}+{{\beta }_{1}}\cdot 
X+\epsilon $, where $\theta$ is an estimated parameter (e.g., $\phi$, 
$\gamma \prime$, $\gamma\prime\prime$), $\beta_0$ is the intercept, 
${{\beta }_{1}}$ is the effect of covariate $X$, and $\epsilon $ is 
residual error. Additionally, auxiliary information can be used to 
inform parameter estimates. For example, telemetry can be used to 
determine whether a pallid sturgeon is in the study area or not and 
thereby inform estimates of $\gamma \prime$and $\gamma\prime\prime$. 
Overall ability of a capture recapture robust design to use auxiliary 
information and potential capture population level responses to 
management actions make this a potentially useful design beyond 
providing a means to quantify the metrics and targets for sub-objectives 
1 and 2. 


Caveats and considerations
Monitoring pallid sturgeon in a system as large as the Missouri River is 
inherently challenging and it is likely that any approached used will 
violate an assumption required to estimate demographic rates or 
population abundance. The previous section provides an overview of the 
robust design as a monitoring design for pallid sturgeon populations of 
the Upper and Lower Missouri River. The accurate estimation of 
population parameters represents a critical component of assessing the 
system state for pallid sturgeon in the Missouri River and providing key 
demographic values for evaluating management actions through predictive 
population modeling. The estimation of these metrics depends on the 
quality and quantity of data collected from a well-developed sampling 
design. The optimal design must be cost-efficient, and provide reliable, 
accurate data. 

Implementing an untested design on a large system like the Missouri 
River could prove costly from the expenditure of time and effort if the 
selected design performs poorly. Pallid sturgeon populations in the 
Upper and Lower Missouri Rivers differ (e.g., size and age at maturity, 
growth rates, life span). The habitats in which they live are also 
different. The Lower River is characterized by a narrow, self-scouring 
channel with higher water velocities, especially in the main channel. In 
contrast, the Yellowstone and Upper Missouri Rivers are characterized by 
lower velocities, shallower depths, and a more natural channel form. 
Differences between the two Missouri River portions has shown that the 
most effective sampling methodologies and potential strategies also 
differ significantly and therefore necessitate that the mark-recapture 
sample designs be tailored to each population. Provisional capture 
recapture population monitoring designs need to be evaluated by 
simulation modeling to identify the optimal design (that is, tradeoffs 
between precision, bias, and cost) and provide proof of concept before 
testing or implementing in the field as part of a level 1 science effort 
and adjusted periodically to improve the design so that it more 
effectively meets the monitoring and species objectives. 
-->
