---
title: "White Paper
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "Missouri River Pallid Sturgeon Technical Team"
output:  
  html_document:
    theme: readable
    highlight: tango
  pdf_document:
    highlight: zenburn 
  word_document:
    highlight: zenburn
---

<!--
To do:
1. utility for model
-->

# Fundamental objectives

## Quantify PS recruitment to age 1.
 
## Provide estimates with associated uncertainty needed to run the PS population model

## Quantify PS population trend

## Maintain compatibility with legacy data


## Cost

Cost is the ultimate PSPAP constraint. Designs exceeding cost 
containments will not be considered. Significant uncertainty exists in 
costs because of several factors. First, field crews tend to become more 
efficient over time and therefore recent PSPAP costs may not represent 
the actual costs. However, if the next iteration of the PSPAP uses similar 
sampling units (i.e., bends within segments) to the current PSPAP, 
then costs for field sampling will likely be similar. 


### Estimating cost to sample a bend

Estimating cost for a day of sampling is difficult. It is the function 
of several factors, including but not limited to the number of 
personnel, pay rates, other personnel expenses, travel, time sampling, 
and gear maintenance. Additionally, the cost of sampling varies among years
and costs may be non linearly related if there is economy of scale (i.e.,
it may cost less per sampling unit if many are done). 

1. Annual funding provided to each field crew
1. Calculate the number of bends sampled in a year
1. Divide the cost by the total to get a field crew specific
cost per bend. 
1. Model or empirical distribution


* The season will begin when water temperatures decline to 55°F or less 
(in the fall) and will continue through June 30. 
* The Fish Community Season will be July 1 through October 30 throughout 
the geographic range of the PSPAP. 

### Important assumptions

Currently the analysis assumes that the period
of performance for field crews is the same as 
the fiscal year. 

  

```{r,echo=FALSE,warning=FALSE, message=FALSE}

source("_R/6-analysis-cost.R")
hist(depcost[depcost$fieldoffice=="NE",]$perdep)
hist(depcost[depcost$fieldoffice=="CF",]$perdep)

plot(lperdep~year,depcost,
    type='n')
    
    plot(resid(fit)~fitted(fit))
plot(lperdep~ldepcosthat,depcost)    
plot(perdep~year,depcost,
    subset=fieldoffice=="SD")
    
plot(perdep~year,depcost,
    subset=fieldoffice=="MT")
    
plot(perdep~year,depcost,
    subset=fieldoffice=="CF")  
``` 





Quantify PS abundance or relative abundance	 
Quantify catch rates of age 0 and age 1 PS	 
Age at maturity	 
Age structure	 
Blood	 

Catch effort	 
Competition with invasive species	 
Contaminants	 
Didson	 
Diet	 
Disease	 
Drift and dspersal	 
 
Egg quality	 
Egg sample	 
Estimate Effective population size	 
Evaluate annual trends in Native forage fish	 
Fecundity	 
Fin ray	 
Fish communities	 
Fish condition	 
Foraging habitat	 
Free embryo collection	 
Genetic composition	 
Growth	 
Habitat selection	 
 
Hybridization	 
	 
IRC habitat	 
 
Local adaptation	 
 
Microchemistry	 
Model-based estimates of abundance of age 0 and age 1 PS	 
Model-based estimates of survival of hatchery and naturally reproducing PS to age 1	 
Movement	 
	 
Population estimates for PS for all size and age classes, particularly ages 2 to 3	 
Population structure and other characteristics	 
Predation	 
RNA Stress markers	 
Reproductive cycling	 
Reproductive readiness	 
Robust design	 
Sex	 
Sex ratio	 
Spawning aggregation and synchrony	 
Spawning habitat	 
Stable isotopes	 
Stocking program reports	 
 
Stress	 
Survival	 
	 
	 
	 
Use of Mississippi and tributaries	 
Zooplankton density	 
catch rates of all PS by size class	 


Hydroacoustic monitoring
N mixture model	 
PIT tag fish
Trawling
ultrasound
Telemetry River sweep
CJS	 
Calibrated Population Model	
Measure fish length and weight
Take a Tissue sample	
Lavage	 
Stomach removal	
EDNA	
Hatchery report and data	
Closed population estimators
Smaller gill mesh
Use trammel nets



