--- 
title: "PSPAP Reboot"
author: "Michael E. Colvin"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
---
```{r,echo=FALSE}
library(knitr)
```

<!--
# COPY FILES TO DOCS FOR GITHUB.IO
bookdown::render_book("",output="bookdown::gitbook",
    output_dir = "C:/Users/mcolvin/Documents/projects/Pallid Sturgeon/Analysis/PSPAP-Reboot/docs")
-->

# Missouri River pallid sturgeon declines and recovery program

Population Assessment Approach
The approach evaluated here was designed to inform pallid sturgeon monitoring and assessment objectives and integrate with the Pallid Sturgeon population model.  The core of sampling effort is based on a robust design and an integrative population model proposed to serve as the population inventory framework assimilating data needed to estimate parameters for the population model, calibrate catch data, and to provide a check on population estimate trends.  The objectives of the population assessment approach described here is to develop and approach that:  1) informs objectives and sub-objectives, 2) informs population model, and 3) cross walk to legacy catch data.  To meet these objectives several components of Pallid Sturgeon monitoring need to be formally integrated such that efforts provide usable information (Figure 1)





## Marked populations




Abundance

Site-level

* How many replicates are needed to estimate abundance reliably?  What is reliable?
    * Constant p
    * Heterogeneous capture probability
    * Some movement in and out
* Benefit of using tagged critters?

Segment-level

* Estimates from 25% of bends in segment per year?
* Dependent on bend size
* Relate to density?
* Consequences of some movement?

Survival

* Robust design
    * M0- varies by bend $\text{logit}(p)={{\beta }_{0}}+{{\beta }_{1}}\cdot Bend$
    * Mt – varies by bend and secondary occasion $\text{logit}(p)={{\beta }_{0}}+{{\beta }_{1}}\cdot Bend+{{\beta }_{2}}\cdot Occasion+{{\beta }_{3}}\cdot Bend\cdot Occasion$ 
    * Constant phi within segment, varies among years
        * $\operatorname{logit}(\phi )={{\beta }_{0}}+{{\epsilon }_{year}}$ where ${{\epsilon }_{year}}\tilde{\ }N(0,\sigma )$ 
* Robust design with telemetry 
    * In segment (perfect detection, imperfect detection)
    * River sweep (perfect detection, imperfect detection)
        * $\operatorname{logit}(\phi )={{\beta }_{0}}+{{\epsilon }_{year}}$ where ${{\epsilon }_{year}}\tilde{\ }N(0,\sigma )$ 
        * ${{Z}_{track,segement,year}}\tilde{\ }binomial({{\phi }_{segment,year}})$ 
        * River sweep to inform $\phi$, $\gamma \prime $, and $\gamma\prime\prime$from tracking tags

        
1. Do fish move large distances outside of migrations?  What is the optimal time to do capture-recapture? Options: none, some, a lot.  
2. What is better to estimate as a random subset of bends or randomly tag a bunch of fish and recapture in random bends?  

| Option 	|       Model       	| $N_{true}$ 	|               N Bends              	|   Occasions  	|
|--------	|:-----------------:	|:----------:	|:----------------------------------:	|:------------:	|
| V01    	| $p{{(.)}_{bend}}$ 	|    5000    	| 5,7,10,15,20,25,30,35,40,50,75,100 	| 4 to 10 by 1 	|
|        	|                   	|            	|                                    	|              	|
|        	|                   	|            	|                                    	|              	|		
				

BUGS model to estimate close population

`mod<- function()
	{
	for(i in 1:M)
		{
		z[i]~dbin(omega,1) # LATENT VARIABLE, DATA AUGMENTATION
		for(j in 1:T)
			{
			p_eff[i,j]<- z[i]*p_cap # CONDITIONAL SPECIFICATION
			obs[i,j]~dbern(p_eff[i,j])			
			}#i
		}#j
	# DERIVED PARAMETERS
	N<-sum(z[]) 
	
	# PRIORS
	omega~dunif(0,1)
	p_cap~dunif(0,1)
    }`
	
K160: Korman, J., J. Schick, and B. Mossop. 2016. Estimating Riverwide Abundance of Juvenile Fish Populations: How Much Sampling is Enough? North American Journal of Fisheries Management 36:213-229.


Robust design	PSPAP
	PSPAP + telemetry
	PSPAP + river sweep
	PSPAP + telemetry + river sweep
	
Robust design	Random reaches
	Random reaches + telemetry
	Random reaches + river sweep
	Random reaches + telemetry + river sweep
	
                
River bends, defined as a outer bend and crossover were used to simulate spatial dynamics.  The location of individual Pallid Sturgeon were tracked during each time step and moved to a new bend, conditional on survival and previous bend location assuming a multinomial distirubtion as,

Loc_{j,t+\delta t}~Multinomial(p_{I,.,t}

Where varibles and indices are defined in table xx.  The vector of probabilities $p_{I,.,t}$ predicts the proble location given the previous bend location. This approach to movement provided a flexible approach to modeling movement that can be readily related to management actions.  Specifically, $p_{I,j,t} is an array of probabilities with each row summing to one forming a 12 transition matrices providing the probility of moving from bend $i$ to bend $j$. This array of probabilities provides a plugin location for movement.  The diagonal represents the probability of remaining in the same reach, off diagonal elements represent downstream or upstream movements.  

## Management effects on movement
The effect of management actions on movement or drift of adult or larval Pallid Sturgeion respectively can be simulated by modifying monthly transition matrices.  For example, suppose that adult Pallid Sturgeon migrate upstream given a flow or temperature cue.  This directed movement can be simulated by specifying the probability of a fish moving to downstream bends equal to 0 and upstream bends greather than 0.  Similarly, the effect of flow on free embryo drift can be simulated with increased downstream probabilities.  

Y_{I,j,t+1}=\beta_0 + \beta_1 \cdot Q_{I,j,t} for i<=j
i>j = 0

Current model implementation requires an array of transitions for each timestep.  Future model versions will attempt to reefing the linke between environmental covariates like flow such that a time series of predicted flows can be used as as inputs.  The relationship between movement and varying covariates may take the form of a model prediction given previous location.  For example, movement in terms of kilometers could be modeled 

$rkm_{t+1} = \beta_0 + \beta_1 \cdot Q + \beta_2 \cdot rkm_t + \beta_3 \cdot Q \cdot rkm_t + \sigma$.
   
The equation predicts how far, on average, a pallid sturgeon will move given an effect of flow and current location.  The interaction term accounts for the effect of location (i.e., fish cannot move as far if they are near the uppermost bends).  


## Effects on survival

Modeling the effect of management actions on survival is specified by a logistic equation.  Specifically, the base survivals are simulated using the equation 

$\Phi_{stage} = \frac{exp(\beta_0)}{1+exp(\beta_0)}$,

Where $\beta_0$ represents the expected survival on logit scale.  For example, adult survival is expected
               
               
##Capture-recapture of marked Individuals

Historically, individual Pallid Sturgeon were marked with passive integrated transponder (PIT), radio or acoustic tag.  PIT tags provide a way to uniquely identify fish when they are captured, but the amount of information provided by PIT tags is constrained by recapture of the fish.  However if a PIT tagged fish is recaptured, it can inform estimates of survival, origin (i.e., natural, hatchery), and growth.  Alternatively, fish that are tagged with an acoustic or radio tags can be actively tracked or passively detected, informing migration rates, habitat use, and survival.  Using marked fish within a robust design will likely be limited to PIT tagged fish; however use of acoustic or radio tagged fish is discussed below.   
Design and Understanding from Simulations
A preliminary simulation was performed as a proof of concept to evaluate whether a capture-recapture study of individual fish using a robust design would be feasible on a river the size of the Missouri River.  First a geographic template was used based on the current PSPAP river bend sampling units, where a river bends are defined as a three continuous habitats (channel cross-over, inside bend, outside bend) and vary in number and size from for the lower and upper basin (Lower: N=317, mean=4 rkm, min=0.2, max=19; Upper: N=157, mean=2.3, min=0.6, max=8).  Simulations were performed using the lower basin sampling units as templates.  Population dynamics were simulated given known recruitment, survival, and abundance.  Given the population dynamics, capture histories were simulated for two levels of capture probability 0.1 and 0.4.  These values were selected based on capture probability estimates (Rotella and Hadley 2010, Steffensen et al. 2015).  These simulated capture histories were then used to estimate population abundance, survival, and recruitment.  The robust design estimator used was the simplest case, assuming homogenous capture probabilities among secondary sampling units and that capture probability was homogenous among bends.  The simulation used 5 primary sampling periods and varying secondary sampling occasions (2 through 10) to evaluate estimator performance, reliability, and effort levels.    
Within a primary sampling occasion at least 2 secondary capture occasions are required to estimate the population using capture-recapture of marked individuals and more are likely needed if heterogeneous capture probabilities are present.  Over a spatial extent, sampling at least 20% of the river bends was necessary in preliminary simulations.  While this preliminary simulation does not address specific gears, selecting gears and sampling occasions that maximize catch will likely result in reduced effort.  Based on preliminary analyses, the population abundance could be estimated (Figure 2).  With the exception of a capture probability of 0.1 reasonable abundance estimates were achieve by sampling 20% of the bends if capture probability was 0.4 (Figure 2).  If capture probability was 0.1 either more bends needed to be sampled or 6 or greater sampling occasions.  There was no appreciable effect of increased secondary occasions to estimate population abundance if capture probability was 0.4.  It should be recognized these simulations were conducted under the best case scenario (i.e., homogenous survival and capture probability) and therefore may not reflect the challenges to sampling a large turbid river like the Missouri River and additional study is required to evaluate ‘worst case’ scenarios.  
 Additional Information to Complete Design
This simulation study is preliminary and suggests that a robust design mark recapture approach may be a useful monitoring approach.  To fully complete the robust design, a level 1 study should be implemented to evaluate spatial and temporal configurations required to achieve acceptable population and demographic rate estimates.  Additionally, if the monitoring program will be used to detect the effect of management actions, a power analysis must be completed.  The amount of effort required to provide reasonable estimates should be considered.  Lastly, including auxiliary information such as data from tagging arrays or river tracking in an integrated population model will provide a unifying framework incorporating system level monitoring and providing estimates and feedback necessary to parameterize and calibrate the population model.  
Caveats and considerations
There are many assumptions required to estimate population abundance and demographic rates.  For example, in this preliminary analysis survival and detection probability was constant among primary and secondary occasions, which is likely a poor assumption.  Additionally, factors affecting Pallid Sturgeon survival, such as age, growth, condition were not evaluated and should be accounted for to improve estimates and also capture the effect of these variables on survival such that they can then be potentially linked to management actions.  Additional research will be required to evaluate the tradeoffs of efforts with estimate bias and precision.  Also, evaluation of how sensitive estimates are to violation of assumption will be necessary prior to implementation of monitoring programs.  Lastly, the monitoring design will have to be optimized within the constraints of the finite resources available to monitor Pallid Sturgeon on an annual basis, which is not a trivial task in a large turbid system like the Missouri River.    
               
                