# Robust Design Overview
The population assessment approach proposed is what is referred to as a robust design (Pollock 1982, Kendall 1997).  As originally described by Pollock (1982), a robust design consists of primary sampling occasions with secondary sampling occasions nested with the primary sampling occasion.  Primary occasions are spaced temporally to capture processes such as survival and growth.  Secondary occasions occur over a short timeframe, short enough that closure of the population from demographic processes (i.e., recruitment, mortality, immigration, emigration) can be assumed.  The secondary sampling occasions also provide multiple opportunities for individuals to be captured, allowing for the estimation of capture probability providing an estimate of the population rather than an index of relative abundance.  True abundance estimates are important to ongoing adaptive management and recovery because species recovery objectives and sub objectives are specified as abundance and population growth rate ($\lambda $) is estimated as $\lambda ={{N}_{t+1}}/{{N}_{t}}$ where $N$ is population abundance.    

The robust sampling design has been applied across a wide range of taxa to estimate demographic rates and population abundance.  The robust design was originally conceived to provide a robust population estimates derived from open capture-recapture models, the Jolly Seber model in particular.  Its use has been extended to studies of species occurrence (i.e., occupancy models; MacKenzie et al. 2002, Tyre et al. 2003) and abundance (N-mixture models; Royle 2004b, Royle 2004a) of unmarked individuals.  Therefore it provides a rigorous framework that allows for the estimation of relevant demographic rates and abundance, using marked or unmarked individuals.  It should be recognized that monitoring Pallid Sturgeon in a system as large as the Missouri River is inherently challenging and it is likely that any approached used will violate an assumption required to estimate demographic rates or population abundance.  The following sections provide a preliminary overview of the robust design as a potential monitoring design for Pallid Sturgeon populations of the Upper and Lower Missouri River.  
