# Pradel model




## Background

The information contained in capture histories informs the survival from one time interval to the next.  
This information when viewed in reverse order contains information on entry into the population.
Specifically, prior to being captured a critter is either at large (present but not captured) or not present (i.e., unborn).
Therefore looking at capture histories in reverse order estimates recruitment.
Typical with capture-mark-recapture approaches estimated parameters can be estimated and related to covariates.


The Pradel model originally developed by Pradel back in the 70s estimates survival and recruitment using this reversal symmetry.
Essentially, when looking at a capture history of a fish in reverse with particular examination of the preceding 0s.
Suppose a capture history of a fish is 00010101, on the first 3 occasions a fish could be alive and not captured or waiting to be born.
Using this information a cmr program may be able to simultaneously model survival and recruitment.
This is appealing because recruitment can be thought of simply surviving age-0 or age-1 which can be related to covariates.
Thinking outside of the box on this one might be able to model the effect of environmental covariates hypothesized to influence recruitment.   


The objective of this brief is to explore whether this might make sense.  It is not a full proof of concept but a simple what if.
Therefore the usual caveats are at work here, specifically this might work well on a computer but may fail miserably in the field.

## Simulating some known data.

To test the approach we need to simulate some data from some known parameters.  
The Pradel model estimates $\phi$, $p$, and $f$, where these values represent survival, capture probability, and recruitment rate.

For the simulation I simulated 10 occasions, could be 10 years, 10 months, so on.

* Survival $\phi$ was set at 0.8
* Capture probability $p$ was set at 0.3
* Recruitment rate $f$ was set at 0.195 (i.e., Recruits = $f$*Abundance)
* Initial population was set to be 2000 critters

The code above simulates a population of individuals given a recruitment rate where the number of recruits is a function of the population in this case.
It may not be in some cases and this can be account for in the Pradel formulation.
Now we can look at the 'true' population dynamics.

Now we can use the 'true' population dynamics to simulate the capture process and make some capture histories.



In the capture histories there are fish that were present but not captured, we need to drop those from the histories.

The library 'Rmark' gets us access to program mark through R which we can we to set up the capture histories and design matrices.

Now that the data is all set up we can feed some formulas for $\phi$, $p$, and $f$ to MARK for estimation.
These are all time invariant formulations (i.e.,$\phi$, $p$, and $f$ are constant over time). 


You can also recast the model to estimate lambda.


Neat, the lambdas for each year are XXXXX with a 95% CIs of 
xxxxx.
That seems reasonable the population looks to be decreasing over time and hence lambda < 1.  


## Application to AM and the big picture

The potential application of this is linking managment actions to demographic rates.
For example suppose over the 10 years IRC habitat was constructed and hypothesized to influence recruitment.
Well in this case we can simulate that is in fact the case.  
First we need to set up the relation between IRC and recruitment rate.
The effect is modeled using a log link. 
For this example the baseline recruitment rate is 0.26 (the log of that is -1.33) and is the intercept of the equation.
The effect of IRC, which might be measured in area is 0.003.
Putting those together the equation to predict recruitment rate is $f= exp(\beta_{0} + \beta_{1} \cdot IRC)$
The code below implents this for some IRC values.


The predicted recruitment as a function of IRC looks like the figure below.

### Fitting a covariate to recruitment

Using the same code to simulate a population with constant $\phi$ as above but now allowing $f$ to vary over time as a function of IRC we can simulate the population data.


The population dynamics are plotted below.



Now that we have the true population data we can simulate the capture histories given $p$

Some processing of the simulated data to feed to MARK.

Now we can do as we did previously but now there is a new bit relating $f$ to IRC `f.irc=list(formula=~irc+1)`.

Well the estimates look good, I fed the simulation a $\beta_{0} = r B_0$ and got back ` coef(m1)[3,1]`.
For the effect of IRC I used a $\beta_{1} = r B_irc$ and got back r coef(m1)[4,1].

  
**Estimates and true values will not exactly match but will improve with more occasions, recaptures, and so on.**
 
A information theoretic appraoch could be used to evalaute the effect of IRC versus no effect of IRC.

With AICc values of r round(summary(m1)$AICc,2) and 
 r round(summary(m2)$AICc,2) for m1 and m2 respectively there might be some weak evidence for an effect of IRC.



### Fitting a covariate to lambda

Using the same approach we can fit a covariate to lamba.  This is not as directly interpretable but simply illustrates the approach.

## Caveats

1. This approach may be useful, or not, but may warrant consideration.
1. The approach will not get at abundance and therefor will not be useful for getting at some objectives.
2. It is dependent on many assumptions and conditions and as we all know working on a big river throws some big monkey wrenches.
3. This simulation made a number of simplifying assumptions, constant $\phi$, constant $p$ which may be relaxed to a degree.
5. The consequence of violating the assumptions is always problematic.  

