


source("_R/1_global.R")
source("_R/2_functions.R")
source("_R/3_load-and-clean.R")

## QUERY LENGTH WEIGHT DATA FROM PSPAP DATABASE
com99<- odbcConnectAccess2007("C:/Users/mcolvin/Documents/projects/Pallid Sturgeon/Analysis/PDSG-LW/dat/dat.accdb")
eff<- sqlFetch(com99,"eff")
fish<- sqlFetch(com99,"fish")
stocked<- sqlFetch(com99,"stocked")
genetics<- sqlFetch(com99,"genetics")

names(eff)<-tolower(names(eff))
names(fish)<-tolower(names(fish))
names(stocked)<-tolower(names(stocked))
names(genetics)<- tolower(names(genetics))

genetics[genetics==""]<-NA
genetics$pittag_1<- toupper(genetics$pittag_1)
genetics$pittag_2<- toupper(genetics$pittag_2)
stocked$pit_tag<- toupper(stocked$pit_tag)
stocked$pit_tag_2<- toupper(stocked$pit_tag_2)
fish$tagnumber<- toupper(fish$tagnumber)


# CLEAN AND MANINIPULATE
tmp<- merge(eff,fish,by.x="uniqueidentifier",by.y="uniqueid")

# SUBSET OUT FISH THAT ARE OUTLIERS 
tmp<-subset(tmp, !is.na(length))
tmp<-subset(tmp, !is.na(weight))
tmp<- subset(tmp, length>0)
tmp<- subset(tmp, weight>0)
tmp<-subset(tmp,species=="PDSG")
tmp$llength<-log(tmp$length)
tmp$lweight<-log(tmp$weight)
fit<-lm(lweight~llength,tmp)
tmp$pred<- exp(fitted(fit))
tmp$residual<- resid(fit)
tmp<- subset(tmp, residual> -1.5)
tmp<- subset(tmp, residual< 1.5)
tmp<- subset(tmp, length>=200)
tmp<- subset(tmp, year>=2015)
out<-data.frame()
quantiles<- seq(0,100,by=1)/100
for(seg in unique(tmp$segment_id))
    {
    q<-quantile(tmp[tmp$segment_id==seg,]$length, quantiles,
        na.rm = TRUE)
    app<- data.frame(segment=seg,quantile=quantiles,val=q)
    out<- rbind(out,app)
    }

out<-out[order(out$segment, out$quantile),]
#write.csv(out,"_output/length_inputs.csv")

head(out)


library(lattice)
presPlot()
out<-subset(out,segment %in% c(2,3,4,7,8,9,10,13,14))
out$segment<- factor(out$segment) 
xyplot(quantile~val,
    data=out,lwd=3,
    groups=segment,
    subset= segment %in% c(2,3,4,7,8,9,10,13,14),
    type='l',
    xlab="Length",
    ylab="Quantile",
    auto.key=list(columns = 1,
        title="Segment",size=3,
        space="right",
        lines=TRUE,
        points=FALSE))
dev.off()
out<-subset(out,segment %in% c(2,3,4,7,8,9,10,13,14))
out$segment<- factor(out$segment) 

plot(quantile~val,data=out,
    xlab="Length, mm",
    ylab="Quantile",
    type='n',las=1,tck = 0.02)
points(quantile~val,data=out,subset=segment==2,type="l",lty=1,lwd=2,col='grey')
points(quantile~val,data=out,subset=segment==3,type="l",lty=2,lwd=2,col='grey')
points(quantile~val,data=out,subset=segment==4,type="l",lty=3,lwd=2,col='grey')

points(quantile~val,data=out,subset=segment==7,type="l",lty=1,lwd=2)
points(quantile~val,data=out,subset=segment==8,type="l",lty=2,lwd=2)
points(quantile~val,data=out,subset=segment==9,type="l",lty=3,lwd=2)
points(quantile~val,data=out,subset=segment==10,type="l",lty=4,lwd=2)
points(quantile~val,data=out,subset=segment==13,type="l",lty=5,lwd=2)
points(quantile~val,data=out,subset=segment==14,type="l",lty=6,lwd=2)
axis(3,at=axTicks(1),labels=FALSE,tck=0.02)
axis(4,at=axTicks(2),labels=FALSE,tck=0.02)
legend("bottomright",
    legend=c(2,3,4,7,8,9,10,13,14),
    lty=c(1:3,1:6),
    col=c(rep("grey",3),rep("black",6)),
    title="Segment",bty="n",ncol=2,lwd=2)
savePlot("C:\\Users\\mcolvin\\Documents\\projects\\Pallid Sturgeon\\Analysis\\PSPAP-Reboot\\images\\fig4.pdf",
type='pdf')
