---
title: BDN Nodes
output: 
  html_document:
    includes:
      in_header: header_banner.html 
bibliography: PSref.bib
csl: ecology.csl  
---


Model inputs for RPMA 2 and 4

## INPUT
input$upper$maxage<-60
input$upper$sexratio<-0.5
input$upper$natural<- 12
input$upper$hatchery<- 43000
input$upper$natural_age0<- 200
input$upper$hatchery_age0<- 0

# WEIGHT-LENGTH

input$upper$a_prime<- -14.09
input$upper$b<-3.24
input$upper$lw_er<-0.165

# FECUNITY-LENGTH
input$upper$fec_a<-11.26
input$upper$fec_b<-0.57
input$upper$fec_er<-0.39

# GROWTH
input$lower$maxLinf<-1800
input$lower$ln_Linf_mu<-6.982160
input$lower$ln_k_mu<- -2.382711
input$lower$vcv<- matrix(c(0.0894,-0.1327,-0.1327,0.3179),nrow=2,ncol=2, byrow=TRUE)

## SEXUAL MATURITY AND RETURN TO SPAWNING	

input$upper$age_mat<-8  ####fixme#### make it work for lower and upper
input$upper$mat_k<-0.2 	####fixme#### make it work for lower and upper
input$upper$spn_a<- -5
input$upper$spn_b<- 2.5

## SURVIVAL
input$upper$pr_embryo<- 0.0001
input$upper$phi_embryo<- 0.0001
input$upper$phi_free_embryo<- 0.0001
input$upper$phi_age0_mean<-0.0001
input$upper$phi_age0_er<-0.01
input$upper$phi_age1_mean<-0.95
input$upper$phi_age1_er<-0.1
input$upper$phi_age2_mean<-0.95
input$upper$phi_age2_er<-0.01



## STOCKING ##
### FINGERLINGS
input$stockingInput$fingerling<-c(0)
input$stockingInput$fingerling_month<-c(5)
#input$stockingInput$fingerling_mn<-c(30)
#input$stockingInput$fingerling_sd<-c(0.1)
input$stockingInput$fingerling_stocking_rkm<-c(50)
### YEARLINGS
input$stockingInput$yearling<- 0
input$stockingInput$yearling_month<- 9
input$stockingInput$yearling_mn<- 100
input$stockingInput$yearling_sd<- 15
input$stockingInput$yearling_age<- 15 # months
input$stockingInput$yearling_stocking_rkm<- 50

## SPATIAL INPUTS ##
### SPATIAL STRUCTURE
input$spatialInput$adult_spatial_structure<- "Uniform" # "Empirical"
input$spatialInput$age0_n_spatial_structure<- "Uniform"# "Empirical"
input$spatialInput$age0_h_spatial_structure<- "Uniform"# "Emperical"


