
<!--
Chapter 2

to do:

-->

# Estimating pallid sturgeon abundance 

## Overview 

## Abundance


## Site-level

* How many replicates are needed to estimate abundance reliably? What is 
reliable? 
    * Constant p
    * Heterogeneous capture probability
    * Some movement in and out
* Benefit of using tagged critters?


## Segment-level

* Estimates from 25% of bends in segment per year?
* Dependent on bend size
* Relate to density?
* Consequences of some movement?

## Major questions 

Each major question corresponds to a chapter in this report.


Chapter 3. How many occasions are needed to estimate abundance at the 
bend-level and segment level? 
Chapter 4.. How should segment estimates be aggregated? 
    1. Derived from average bend estimates?
    2. Estimated at the segment level from bend-level data?
3. Do acoustic tags help in reducing the number of occasions? 
    1. If so how many tags are needed? 
    2. Can segment sweeps help in estimating segment level abundance?
4. What is the value of using shovelnose to estimate a common capture 
probabilities? 


BUGS model to estimate close population

`mod<- function()
	{
	for(i in 1:M)
		{
		z[i]~dbin(omega,1) # LATENT VARIABLE, DATA AUGMENTATION
		for(j in 1:T)
			{
			p_eff[i,j]<- z[i]*p_cap # CONDITIONAL SPECIFICATION
			obs[i,j]~dbern(p_eff[i,j])			
			}#i
		}#j
	# DERIVED PARAMETERS
	N<-sum(z[]) 
	
	# PRIORS
	omega~dunif(0,1)
	p_cap~dunif(0,1)
    }`
	

